FROM node:20.18.2-alpine AS frontend
WORKDIR /app

COPY . .

RUN apk add git

RUN yarn global add @quasar/cli

RUN cd frontend && \
    yarn install && \
    yarn build/web/dev


FROM flipperdevices/nginx-headers-more-alpine:1.25.1

RUN apk add tzdata

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=frontend /app/frontend/dist/spa /usr/share/nginx/html

EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
